#include "interface2platform.h"
interface2platform::select_accum()
{
}
interface2platform::consume_accum()
{
}
interface2platform::add_accum()
{
}
interface2platform::http_client_connect()
{
}
interface2platform::http_client_send()
{
}
interface2platform::http_client_parse_response()
{
}
